### ISSUE TITLE
Project Dead / DRM issues

### ISSUE THREAD

**Issue by gorfreed** [sightread/midishare#18]
I find this app in all the forums I have searched to find usable Synthesia midis, but the page contains a library of ... 9 songs. None of the commenters pointed that out which got me curious. Looking at the screenshots here at Github, I can see there were actually more songs that are not unavailable. My guess is the project is dead because of DRM issues - is that correct?

**Comment by samouri** [comment]
- Project lost a lot of songs when I became concerned about DRM issues. 
- That is separate from the reason it has little activity though. I've mostly stopped working on all my projects due to starting a new (relatively demanding) full-time job. I still plan to come back to this, but in the timescale of 6 months not a few weeks.

**Comment by gorfreed** [comment]
I appreciate your quick reply! It's kind of a bummer that Synthesia never grew a community that would support projects like yours. Wish you all the best for your future endeavours!

**Comment by samouri** [comment]
@gorfreed: I added a whole host of new songs. Going to close this
